### ISSUE TITLE
Set up nestdoor repo

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#10]
Story:
As a developer, I need to set up the basic repo for our app.

**Tasks:**
- [x] Create the app with Django.
- [x] Implement proper GitHub organization like labels.
- [x] Ensure proper files are present like a git ignore file, README file, src folder, etc.
- [x] Implement access for all team members to be able to properly contribute to the repo.

**Acceptance:**
1. All proper default folders and files are present and ready in order for developers to add to the app.
2. Pulling from the repo ensures proper developers are able to do so with no issues.
3. Developers are able to use the GitHub features to the fullest like issues, labels, pushing, etc.
