### ISSUE TITLE
Deployment Debugging

### ISSUE THREAD

**Issue by ktracy2** [COSC481W-2023Fall/nestdoor-app#19]
Story:
As a developer, I need to deploy the app on Digital Ocean successfully, including static files. 

**Tasks:**
 - [x] Create static site to run alongside the app for static files to "live"
 - [x] Configure static urls/paths in settings.py
 - [x] collectstatic files 
 - [x] Create deployment branch that will be used as a source for deployment

**Acceptance:**

Digital Ocean builds and deploys the app without fail.  
Static files (css and images) are available.  Styling and images are visible on deployed site.
