### ISSUE TITLE
User account creation

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#3]
**User Story:**
As a user, I want to be able to create an account.

**Tasks:**
- [x] Prepare the database to store the user's email, username, and password
- [x] Correctly store those so that when the user creates an account, the information is retained in the UI.
- [x] Deal with the case where a user's email or username is already taken.

**Acceptance Criteria:**
1. If the user leaves the username, email, or password fields blank, a warning is shown and they can not continue making an account until they fill all those fields in.
2. If the user fills in an already taken username or email, then the user account is not created and a warning is shown.
3. Standard password criteria are followed to ensure the password has a mix of lowercase and uppercase letters, numbers, etc.
4. When a user creates an account, the UI updates to no longer show the "SIGNUP" or "LOGIN" links/ buttons and instead shows the user's username.
