### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#4]
**User Story:**
As a user, I want to be able to log in so that I can start using the app (posting, reading more posts).

**Tasks:**
- [x] Prepare the database to retrieve the user's email, username, and password.
- [x] When a user logs in, log-in is retained even after a page refresh or exit.
- [x] Shows proper UI changes to establish user is indeed logged in.

**Acceptance Criteria:**
1. Correctly retrieves that information from the database so that when the user logs in, the correct user is logged in.
2. If the user attempts to log in without a username, email, or password, then a warning is shown.
3. If the incorrect combination of username, email, and password is entered then a warning is shown.
4. When a user logs in, the UI updates to no longer show the "SIGNUP" or "LOGIN" links/ buttons and instead shows the user's username.

**Comment by gtcolling** [comment]
Completed. Do I need to request a merge with the branch?
