### ISSUE TITLE
User detailed posts

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#47]
**User Story:**
As a user who wants to interact more with people, I want to see a more detailed view of the post so I can engage with it more.
* Persona: A user who wants to interact more with people
* Feature: A detailed enlarged post from the user's post in the forum
* Business Value: Users can engage more on a more fulfilling level with each other

**Tasks:**
- [x] Prepare the database to retrieve information so the proper post and corresponding user are displayed
- [x] Create a default User post page that has room for the user's posts and comments.
- [x] Create proper scaling for the text posts.
- [x] Create tests to make sure the page is displayed properly.
- [ ] Merge the working branch back to the main branch and test to make sure everything works properly.

**Acceptance Criteria:**
1. Correctly retrieves that information from the database so the proper post and corresponding user are displayed.
2. Posts are able to be scrolled through and enlarged properly.
