### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#48]
**User Story:**
As a user who wishes to engage more with the app, I would like to see and edit my profile page so that I can see what I have contributed to the app.
* Persona: A user who wishes to engage more with the app.
* Feature: A user profile page
* Business Value: Users can engage more with the app by seeing all their contributions, which may encourage them to engage with the app more.

**Tasks:**
- [x] Retrieve information from the database to show the proper user's username corresponding "about me" information.
- [x] Show the user's corresponding contributions to the app, like their amount of posts and comments.
- [ ] Allow the user to edit their about me information.
- [x] Create tests to make sure the page(s) are displayed properly.
- [ ] Merge the working branch back to the main branch and test to make sure everything works properly.

**Acceptance Criteria:**
1. If the user is NOT logged in, clicking on a user's profile page only shows them their about me information and contribution statistics.
2. If the user IS logged in, clicking on a user's profile page only shows them their about me information and contribution statistics.
3. If the user IS logged in, clicking on their profile page shows them their about me information and contribution statistics. They are also allowed to edit their about me information. 
4. If the user starts to edit their "about me" information and does not save their changes and attempts to exit the page or refresh, they are given a warning.
