### ISSUE TITLE
Create a post on the Forum page

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#49]
**User Story:**
As a user who wishes to contribute to the app, I want to post some text to the forum so that I can put my suggestions or thoughts into the forum.
* Persona: A user who wishes to contribute to the app.
* Feature: Creating a post on the forum page
* Business Value: Users can engage more with the app by contributing to the app with their post.

**Tasks:**
- [x] Edit the forum page to have proper space and scrolling for posts.
- [x] Ensure the user's usernames are shown directly next to their corresponding posts.
- [x] Prepare the database to hold user's text posts.
- [x] Create a "create post" button that when clicked on, allows the user to type.
- [x] After a user is done creating a post, have a "publish post" button that publishes the post in the forum.
- [x] Have proper precautions to ensure appropriate material is published and nothing is inappropriate. 
- [ ] Create tests to make sure the forum page is properly displayed and creating posts works.
- [ ] Merge the working branch back to the main to see if everything works properly together.

**Acceptance Criteria:**
1. If the user attempts to post something inappropriate, they are given a warning, and the post is NOT published.
2. If the user attempts to exit or refresh the page while creating a post, they are given a warning.
3. If the user attempts to create a post but they are not logged in, then redirect them to the login page.

**Comment by sjiang1** [comment]
Some tasks are marked done, but I can't find a branch linked to this issue.

**Comment by gtcolling** [comment]
> Some tasks are marked done, but I can't find a branch linked to this issue.

I got the branch added, thank you!
