### ISSUE TITLE
Logo and On-Click Redirects

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#5]
User Story:
As a user, I wish to see a logo for the homepage that redirects to the homepage when clicked on. I also wish to see the mini logo in the banner and footer that directs to the homepage.

**Tasks:**
- [x] Design a main logo and mini logo for the website.
- [x] Connect the images to links to the homepage.
- [x] Create a background using the main logo (small-medium sized, repeating, semi-opaque) 
- [x] Ensure clicking on the mini logo leads to the homepage.

**Acceptance Criteria:**
1. If a user clicks on the main or mini log, they are redirected to the homepage. 
2. If a user clicks on these even while on the homepage, a simple refresh of the page is performed. 
3. If a user hovers over these logos, the cursor turns into a pointer to indicate the logo is clickable.
