### ISSUE TITLE
Edit an existing post

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#50]
**User Story:**
As a user who wishes to make changes to their posts, I want to edit one of my posts in a forum so that I can make any changes or updates to my post after posting
* Persona: A user who wishes to make changes to their posts.
* Feature: The ability to make edits to already existing posts.
* Business Value: Users can feel more fulfilled because they are able to change their posts and contribute more effectively to the app.

**Tasks:**
- [x] Prepare the database to make changes to users' text posts.
- [x] Create an "edit post" button on a user's post that allows them to change the contents of their post.
- [x] After a user is done updating a post, have an "update post" button that updates the post in the forum.
- [ ] Have proper precautions to ensure appropriate material is published and nothing is inappropriate.
- [ ] Create tests to make sure that updating posts works.
- [x] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If a user is NOT logged in and clicks on their post in the forum, they should not be allowed to make changes to it. The "Edit post" button should appear at all.
2. If a user is NOT logged in and clicks on a random user's post in the forum, they should not be allowed to make changes to it. The "Edit post" button should appear at all.
3. If the user IS logged in and clicks on their post, they should be allowed to make changes to it. The "Edit post" button should appear.
4. If the user attempts to post something inappropriate, they are given a warning, and the post is NOT updated.
5. If the user attempts to exit or refresh the page while updating a post, they are given a warning.
