### ISSUE TITLE
News Feed 

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#51]
**User Story:**
As a user who wishes to be kept up to date on the latest happenings in the app, I wish to see a news feed that shows all the relevant information.
* Persona: A user who wishes to be kept up to date on the latest happenings in the app.
* Feature: A news feed that shows all the latest news relevant to the app.
* Business Value: Users can feel more fulfilled because they are able to view what's been happening lately in the app itself.

**Tasks:**
- [ ] Create a news feed page that has the proper space for the latest news.
- [ ] Prepare the app to hold this information.
- [ ] Ensure proper scaling and scrolling are implemented.
- [ ] Shows columns that each contain some piece of news relevant to the app. This could be trending forum posts or new happenings in EMU.
- [ ] Each column of information shows the date and time that they were added to the news feed.
- [ ] Clicking on a piece of news redirects the user to the proper forum post, piece of news, etc.
- [ ] Create tests to make sure the news feed page is shown properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If the user clicks on a piece of news, they are redirected to the appropriate resource.
