### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#52]
**User Story:**
As a user who always forgets their passwords, I wish for the option to recover and or change my password to be available. 
* Persona: A user who always forgets their passwords.
* Feature: The ability for a user to recover and or change their password.
* Business Value: Users can feel like they are never locked out of their account so they can keep engaging with the app.

**Tasks:**
- [x] Prepare the database to retrieve a user's username and corresponding password. 
- [x] Prepare the database to change a user's password. 
- [x] When the login page is displayed, give a prompt for the user to recover their password. Something like "Forgot your password?" 
- [x] Once forgot password is selected, user can input their email to receive further password reset information
- [x] Create tests to make sure that recovering passwords work properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If the user does not input their correct user email, a password reset email will not be drafted
2. If the user redirects to the password reset request page, but does not enter an email they can go back to the homepage
3. After submitting an email to the password reset request, the user will be redirected back to the login page with a message informing them of next steps
