### ISSUE TITLE
Clicking user profiles in Forum lead to user profiles

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#53]
**User Story:**
As a user who wishes to see what other contributions other users have made, I wish to click on a user's username in the forum and be brought to their profile page.
* Persona: A user who wishes to see what other contributions other users have made.
* Feature: The ability to see other user's contributions in a more simplified manner.
* Business Value: Users can more easily see what other users have done right from the forum, which ensures continued use of the app.

**Tasks:**
- [x] Create a direct link between a user's username in the forum to that corresponding user's profile page
- [x] Create a direct link between comments on posts to that corresponding user's profile page.
- [x] Create tests to make sure that the redirecting works properly.
- [x] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If the user clicks on a username, they are directly taken to that corresponding user's profile page. 
2. If the user clicks on their own username in the forum or comments, they are taken to their own profile page.
