### ISSUE TITLE
Comment on another user's detailed post

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#54]
**User Story:**
As a user who always has something to say about someone else's posts, I wish to comment on a post and give my thoughts on that post. 
* Persona: A user who always has something to say about someone else's posts
* Feature: The ability to make comments on other user's posts.
* Business Value: Users can contribute more effectively to the app by providing their own insight and thoughts on other user's posts.

**Tasks:**
- [x] Prepare the database to add users' text posts in the form of a comment that is associated with a specific user's post. 
- [x] Create a "comment" button on a user's detailed post that allows them to publish their comment.
- [x] After a user is done creating a comment, have a "publish comment" button that publishes the comment directly underneath the user's post.
- [x] Have proper precautions to ensure appropriate material is published and nothing is inappropriate.
- [x] Ensure the newest comments are shown at the top of the comment section of the user's detailed post. 
- [x] Implement proper scaling and scrolling for comments.
- [x] Create tests to make sure that publishing comments works properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If a user is NOT logged in and clicks on their post in the forum, they should not be allowed to make changes to it. The "Edit post" button should appear at all.
2. If a user is NOT logged in and clicks on a random user's post in the forum, they should not be allowed to make changes to it. The "Edit post" button should appear at all.
3. If the user IS logged in and clicks on their post, they should be allowed to make changes to it. The "Edit post" button should appear.
4. If the user attempts to post something inappropriate, they are given a warning, and the post is NOT updated.
5. If the user attempts to exit or refresh the page while updating a post, they are given a warning.
