### ISSUE TITLE
Like/Dislike Feature on user posts, comments, news

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#55]
**User Story:**
As a user who wishes to give my thoughts on the quality of a post, I wish to like or dislike something to make my opinion known.
* Persona: A user who wishes to give my thoughts on the quality of a post.
* Feature: The ability to like or dislike a post, comment, or piece of news.
* Business Value: Users can feel more fulfilled because they are able to speak their minds and show what they think of a user's post, comment, or piece of news.

**Tasks:**
- [ ] Prepare the database to hold the like-to-dislike numbers on a specific post, comment, or piece of news.
- [ ] Create a "like" and "dislike" button on a user's detailed post and the comment section.
- [ ] Add either a like or dislike to that post's or comment's ongoing tally of likes and dislikes in the database.
- [ ] Add the "like" and "dislike" buttons to a piece of news on the News Feed page.
- [ ] Add either a like or dislike to that new's ongoing tally of likes and dislikes in the database.
- [ ] Create tests to make sure that the like/ dislike feature works properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If a user clicks like on a post, comment, or piece of news, then they are able to see that they did click that button by way of a visual indicator. 
2. If a user wishes to, they are able to change their mind. If a user first liked a post but then disliked it, the database is used to properly update that tally on that specific post, comment, or news.
3. If a user likes or dislikes a post, comment, or news twice (or more), then only one is counted for both the like and dislike.
