### ISSUE TITLE
News Feed Filters

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#56]
**User Story:**
As a user who wishes to be kept up to date on the latest happenings in the app, I wish to see a news feed that shows all the relevant information that is to my specified liking.
* Persona: A user who wishes to be kept up to date on the latest happenings in the app specific to their tastes.
* Feature: Filters on the news feed page that filters by the user's specified choice.
* Business Value: Users can feel more fulfilled because they are able to view what's been happening lately in the app itself which fits more closely to what they wish to see.

**Tasks:**
- [ ] Prepare the database to retrieve news' and posts' date and time of being added, as well as likes/ dislikes.
- [ ] Create a "filter by" button at the top of the News Feed page.
- [ ] Create filter options for "Date published..." "Time published..." "Most liked..." "Most disliked..." "Top trending..."
- [ ] Create further filter options for "Date published..." and "Time published..." by allowing the user to specify what date and time they wish to see.
- [ ] Shows columns that each contain some piece of news relevant to the app or forum post that is specific ONLY to what the user has specified.
- [ ] Create tests to make sure the news feed page filters work properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If the user filters by "Date published..." and "Most liked..." then those two filter options are combined to show the most liked forum posts or news on that specific day.
2. If the user does not use any of the filters, then the default sorting for the news feed is by the most recent.
