### ISSUE TITLE
Filters for user posts in Forum

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#57]
**User Story:**
As a user who wishes to see only what they want in the forums, I wish to be able to sort by a number of filters in order to accomplish that.
* Persona: A user who wishes to see only what they want in the forums.
* Feature: Filters on the forum page that filter by the user's specified choice.
* Business Value: Users can feel more fulfilled because they are able to view what's been happening in the forum which fits more closely to what they wish to see.

**Tasks:**
- [ ] Prepare the database to retrieve posts' date and time of being published, as well as likes/ dislikes.
- [ ] Create a "filter by" button at the top of the forum page.
- [ ] Create filter options for "Date published..." "Time published..." "Most liked..." "Most disliked..." "Top trending..."
- [ ] Create further filter options for "Date published..." and "Time published..." by allowing the user to specify what date and time they wish to see.
- [ ] Shows forum posts that are specific ONLY to what the user has specified.
- [ ] Create tests to make sure the forum page filters work properly.
- [ ] Merge the working branch back to the main to see if everything works properly together

**Acceptance Criteria:**
1. If the user filters by "Date published..." and "Most liked..." then those two filter options are combined to show the most liked forum posts on that specific day.
2. If the user does not use any of the filters, then the default sorting for the forum posts is by the most recent.
