### ISSUE TITLE
Set up a header bar

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#6]
User Story: 
As a user, I can see the bar going across the top of all the webpages and see the list of all the different pages. 

**Tasks:**
- [x] Design and implement the header bar itself.
- [x] Implement different web pages to populate the bar. 
- [x] Implement text that leads to the proper web pages.
- [x] Implement proper scaling and scrolling.

**Acceptance:**
1. If a user clicks on one of the page titles, that user is redirected to the corresponding webpage. 
2. If the user's cursor hovers over any of the page titles, an indication is given that they are clickable.
3. If the user scrolls down, the header bar follows them and always stays at the top of their screen.
