### ISSUE TITLE
TopNav should be consistent across all pages

### ISSUE THREAD

**Issue by ktracy2** [COSC481W-2023Fall/nestdoor-app#82]
**User Story**
As a user who frequently navigates the pages on your app, I wish for the top navigation bar to be uniform and clean in nature.

- **Persona:** A user who frequently navigates the pages on our app.
- **Feature:** Reformat the top navigation bar to be uniform with each other.
- **Business Value:** Users who are able to see a clean uniform top navigation bar across every page of our app will more than likely return to our app because it's in a consistent state.

**Reference to the Beta Testing Report:**
Salavdor's Beta Testing Report: https://docs.google.com/document/d/1IY_nR1Jhh5Tt_wRP5ex5RCdjqgyIFKtIEpSn4in5IGs/edit?usp=sharing
Item 7:

> Q. Hey, I’m just now noticing that this top bar thingy you have has been different across these pages. What’s up with that
> A. Many different developers each worked on separate pages. Communication was not great, which resulted in some 
> navigation bars looking different or off. Q. Are you going to fix that ‘Logged in as []’ at the top that I keep seeing? What 
> about the two homepage links you have here? Why have two? A. Yes, it will be fixed.
> They clicked on the logout button at the top of the page with no directions and were successfully logged out. After 
> logging out, they began asking questions about the top navigation bar.
> Observations and reflections: This went pretty smoothly. The tester was logged out without issue. However, that top 
> navigation bar needs to be fixed to remove one of the two homepage links, ‘logged in as []’, and make it much more 
> uniform across all pages.
**Tasks**

- [x] Remove the link from the bird icon on the top navigation bar. The birdhouse icon should be the only one that when clicked on, leads to the home page.
- [x] Fix the 'logged in as []' error in the top navigation bar
- [x] Make sure the correct page is highlighted for whatever page the user is on, if applicable.
- [x] Make sure each page has a uniform format throughout.
- [x] Only show the username that leads to their profile page on the top navigation bar if they are logged in for all pages. 
- [x] Merge to main and make sure it's all working correctly.

**Acceptance Criteria**

1. The user clicks on the Home, Forum, About, detailed post, edit post, and profile pages to see a consistent top navigation bar.
2. The bird icon is not clickable.
3. The username only shows up if a user is logged in.
4. Pages are highlighted correctly to show what page the user is currently on, if applicable.
