### ISSUE TITLE
Set up a default homepage view

### ISSUE THREAD

**Issue by SalvadorMedinaRuiz** [COSC481W-2023Fall/nestdoor-app#9]
User Story:
As a user, I wish to see a unified format for the homepage.

**Tasks:**
- [x] Create the basic homepage view.
- [x] Show the basic homepage view upon going to the website by its default URL.
- [x] Implement basic space for header, footer, etc. 

**Acceptance:**
1. Upon going to the correct default URL, the user sees the actual homepage. 
2. Proper formats are used so other developers may implement their necessary stuff.
